### ISSUE TITLE
Avoid to tighly pin dependencies in setup.cfg

### ISSUE THREAD

**Issue by traversaro** [ami-iit/mann-pytorch#2]
Currently the setup.cfg pin quite strictly the used dependencies, see https://github.com/ami-iit/mann-pytorch/blob/60c5ea7335892a622fac2307b60406ef2a44e421/setup.cfg#L20 . In general, this is discourage as it prevents reusability as `mann-pytorch` as a library in projects that require a different version of dependencies, for example once a new version of pytorch is released, it is not possible to use it with mann-pytorch. 

Indeed, pinning too tightly dependencies is discouraged in setup.cfg documentation:

> Library developers should avoid tightly pinning their dependencies to a specific version (e.g. via a “locked” requirements file).
From https://setuptools.pypa.io/en/latest/userguide/declarative_config.html

On the other hand, it is also important to track a set of dependencies against which the library has been successfully tested. Back in time this was the role of the `requirements.txt` file (see https://caremad.io/posts/2013/07/setup-vs-requirement/), but I do not know what is the modern recommendation for this, I did not find anything related to this in https://packaging.python.org/en/latest/ . Perhaps a good old `requirements.txt` with tightly pinned dependencies (but separate from the setup.cfg) is still a good idea.

**Comment by traversaro** [comment]
To give an example from another world, in Julia `Project.toml` is the equivalent of Python's setup.cfg, while there is a separate file to provide the exact dependencies used to test/develop the package, called `Manifest.toml`: https://pkgdocs.julialang.org/v1/toml-files/ .

I do not know what is the equivalent of `Manifest.toml` in Python world.

**Comment by traversaro** [comment]
By looking more into this, I found https://towardsdatascience.com/requirements-vs-setuptools-python-ae3ee66e28af that seems to be still valid. In particular, it quotes the python doc in https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#requirements-files : 

> Whereas install_requires requirements are minimal, requirements files often contain an exhaustive listing of pinned versions for the purpose of achieving [repeatable installations](https://pip.pypa.io/en/latest/topics/repeatable-installs/#repeatability) of a complete environment.

Given this, to solve this issue I proposed to:
* Move exact pinned versions from `setup.cfg`  to `requirements.txt`, leaving just known lower (or upper, if they exist) version bounds of dependencies. 
* Modify docs to specify that `pip -r requirements` before `pip install .` .

**Comment by paolo-viceconte** [comment]
Thanks @traversaro for this issue! I agree on separating strict dependencies from general ones. After doublechecking  whether there are upper version bounds, I will try to implement your suggestions.

**Comment by paolo-viceconte** [comment]
Because of an incompatibility between `tensorboard` and `protobuf`:
```
ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, 
but you'll have protobuf 4.21.5 which is incompatible.
```
an upper bound version for `protobuf` seems actually to be needed.

**Comment by traversaro** [comment]
> Because of an incompatibility between `tensorboard` and `protobuf`:
> 
> ```
> ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, 
> but you'll have protobuf 4.21.5 which is incompatible.
> ```
> 
> an upper bound version for `protobuf` seems actually to be needed.

Are you sure? I tried with `protobuf>=3.9.2` in the setup.cfg, and everything works fine as the pip solver is able to find the protobuf version compatible with the installed tensorboard. I would avoid to put this protobuf constraint as future version of tensorboard may have different protobuf constraints, and the solver is the one whose task is to find the correct version of protobuf.

Actually, it does not seems that the library depends directly on protobuf, probably we can skip listing protobuf as a dependency in the setup.cfg and just let the pip solver install it if necessary? I guess we can keep protobuf in the requirements.txt as it is an important dependency, but I am not sure it plays a role in `setup.cfg` in this case.

**Comment by paolo-viceconte** [comment]
> Actually, it does not seems that the library depends directly on protobuf, probably we can skip listing protobuf as a dependency in the setup.cfg and just let the pip solver install it if necessary? I guess we can keep protobuf in the requirements.txt as it is an important dependency, but I am not sure it plays a role in `setup.cfg` in this case.

By doing so, the installation works indeed fine both if you install the requirements first (as suggested in the updated installation procedure) or not. So I agree on removing the `protobuf` dependency from the `setup.cfg`, such a dependency was likely a leftover.

**Comment by paolo-viceconte** [comment]
Issue addressed by https://github.com/ami-iit/mann-pytorch/pull/3, closing.
